Chapter 8/SpyStore.Mvc/Models/ViewModels/AddToCartViewModel.cs
using System.ComponentModel.DataAnnotations;
using SpyStore.Models.ViewModels;
using SpyStore.Mvc.Validation;

namespace SpyStore.Mvc.Models.ViewModels
{
    public class AddToCartViewModel : CartRecordWithProductInfo
    {
        [Required, MustNotBeGreaterThan(nameof(UnitsInStock)), MustBeGreaterThanZero]
        public new int Quantity { get; set; }
    }
}

Chapter 8/SpyStore.Mvc/Controllers/OrdersController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using SpyStore.Models.Entities;
using SpyStore.Models.ViewModels;
using SpyStore.Mvc.Controllers.Base;
using SpyStore.Mvc.Support;

namespace SpyStore.Mvc.Controllers
{
    [Route("[controller]/[action]")]
    public class OrdersController : BaseController
    {
        private readonly SpyStoreServiceWrapper _serviceWrapper;
        public OrdersController(SpyStoreServiceWrapper serviceWrapper, IConfiguration configuration) : base(configuration)
        {
            _serviceWrapper = serviceWrapper;
        }

        [Route("/Orders")]
        [Route("/Orders/Index")]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "Order History";
            ViewBag.Header = "Order History";
            IList<Order> orders = await _serviceWrapper.GetOrdersAsync(ViewBag.CustomerId);
            return View(orders);
        }

        [HttpGet("{orderId}")]
        public async Task<IActionResult> Details(int orderId)
        {
            ViewBag.Title = "Order Details";
            ViewBag.Header = "Order Details";
            OrderWithDetailsAndProductInfo orderDetails = await _serviceWrapper.GetOrderDetailsAsync(orderId);
            if (orderDetails == null) return NotFound();
            return View(orderDetails);
        }
    }
}

Chapter 8/SpyStore.Mvc/Controllers/ProductsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using SpyStore.Mvc.Controllers.Base;
using SpyStore.Mvc.Models.ViewModels;
using SpyStore.Mvc.Support;

namespace SpyStore.Mvc.Controllers
{
    [Route("[controller]/[action]")]
    public class ProductsController : BaseController
    {
        private readonly SpyStoreServiceWrapper _serviceWrapper;
        public ProductsController(SpyStoreServiceWrapper serviceWrapper, IConfiguration configuration) : base(configuration)
        {
            _serviceWrapper = serviceWrapper;
        }

        [Route("/")]
        [Route("/Products")]
        [Route("/Products/Index")]
        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction(nameof(Featured));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> ProductList(int id)
        {
            var cat = await _serviceWrapper.GetCategoryAsync(id);
            ViewBag.Title = cat?.CategoryName;
            ViewBag.Header = cat?.CategoryName;
            ViewBag.ShowCategory = false;
            ViewBag.Featured = false;
            var vm = _serviceWrapper.GetProductsForACategoryAsync(id);
            return View(await vm);
        }

        [HttpGet]
        public async Task<IActionResult> Featured()
        {
            ViewBag.Title = "Featured Products";
            ViewBag.Header = "Featured Products";
            ViewBag.ShowCategory = true;
            ViewBag.Featured = true;
            IList<ProductViewModel> vm = await _serviceWrapper.GetFeaturedProductsAsync();
            return View("ProductList", vm);
        }

        [Route("[controller]/[action]")]
        [HttpPost("{searchString}")]
        public async Task<IActionResult> Search(string searchString)
        {
            ViewBag.Title = "Search Results";
            ViewBag.Header = "Search Results";
            ViewBag.ShowCategory = true;
            ViewBag.Featured = false;
            var vm = await _serviceWrapper.SearchAsync(searchString);
            return View("ProductList", vm);
        }

        [HttpGet("{id}")]
        public ActionResult Details(int id)
        {
            return RedirectToAction(nameof(CartController.AddToCart),
                nameof(CartController).Replace("Controller", ""),
                new
                {
                    productId = id,
                    cameFromProducts = true
                });
        }
    }
}

Chapter 8/SpyStore.Mvc/Views/Shared/AddToCart.cshtml
@model SpyStore.Mvc.Models.ViewModels.AddToCartViewModel
@{
    ViewData["Title"] = @ViewBag.Title;
}
<h3>@ViewBag.Header</h3>
<form method="post"
      asp-controller="Cart"
      asp-action="AddToCart"
      asp-route-customerId="@ViewBag.CustomerId"
      asp-antiforgery="true"
      id="myForm">
    @Html.EditorForModel()
    <div asp-validation-summary="All" class="text-danger"></div>
</form>
@{
    if (ViewBag.CameFromProducts != null && ViewBag.CameFromProducts)
    {
        <div>
            <a href="#" onclick="window.history.go(-1); return false;">Back to List</a>
        </div>
    }
}
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Chapter 8/SpyStore.Mvc/Views/Shared/LoginView.cshtml
<li class="nav-item navbar-text">Hello <em>Super Spy</em></li>
<li class="nav-item"><a asp-controller="Cart" asp-action="Index" title="Cart" class="nav-link"><span class="fa fa-shopping-cart"></span> Cart</a></li>
<li class="nav-item"><a class="nav-link" href="#"><span class="fa fa-lock"></span> LOGIN</a></li>
<li class="nav-item"><a asp-controller="Orders" asp-action="Index" title="Order History" class="nav-link"><span class="fa fa-tag"></span> Orders</a></li>
<li class="nav-item dropdown search-dropdown">
    <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"><span class="fa fa-search"></span> SEARCH</a>
    <div class="dropdown-menu dropdown-menu-right bg-primary">
        <form asp-controller="Products" asp-action="Search" class="form-inline justify-content-end" role="search">
            <div class="input-group md-4">
                <label class="sr-only" for="searchString">Search</label>
                <input type="text" id="searchString" name="searchString" class="form-control" placeholder="SEARCH">
                <div class="input-group-append">
                    <button class="btn btn-light" type="submit"><span class="fa fa-search"></span></button>
                </div>
            </div>
        </form>
    </div>
</li>

Chapter 8/SpyStore.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpyStore.Mvc</title>
    <environment include="Development,Local">
        <link rel="stylesheet" href="~/lib/bootstrap4/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/lib/fontawesome/css/font-awesome.css"/>
    </environment>
    <environment exclude="Development,Local">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
        <link rel="stylesheet" href="~/lib/fontawesome/css/font-awesome.min.css" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
<header class="navbar navbar-expand-sm navbar-light bg-primary navbar-top">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand d-inline-block d-sm-none" asp-area="" asp-controller="Products" asp-action="Index">SPY STORE</a>
        </div>
        <nav class="collapse navbar-collapse header-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item dropdown categories-dropdown d-block d-lg-none">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">CATEGORIES <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <vc:menu></vc:menu>
                        <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                    </ul>
                </li>
                <partial name="LoginView"/>
            </ul>
        </nav>
    </div>
</header>
    @*<partial name="_CookieConsentPartial" />*@

<div class="page container">
    <div class="card">
        <nav class="card-header d-none d-sm-block">
            <div class="store-logo">
                <a asp-controller="Products" asp-action="Featured"><img src="~/images/store-logo.png" alt="Spy Store" asp-append-version="true"></a>
            </div>
            <ul class="nav nav-pills d-none d-lg-flex">
                <vc:menu></vc:menu>
                <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
            </ul>
        </nav>
        <div class="card-body">
            @RenderBody()
        </div>
    </div>
</div>

<footer class="border-top text-muted">
    <hr/>
    <div class="container">
        &copy; 2019 - SpyStore.Hol.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a><br />
        <email email-name="blog" email-domain="skimedic.com"></email>
    </div>
</footer>

    <environment include="Development,Local">
        <script src="~/lib/jquery/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap4/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development,Local">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>